# syntax=docker/dockerfile:1.4
FROM node:latest

WORKDIR /scratch

RUN git clone https://github.com/sitespeedio/compare.git

WORKDIR /scratch/compare
RUN npm install

ENTRYPOINT ["npm", "run", "develop"]