repos:
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  - id: trufflehog
    name: TruffleHog
    description: Detect secrets in your data.
    entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
    language: system
    stages: ["commit", "push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
