# syntax=docker/dockerfile:1.4
FROM nginx:1.23.1 

COPY <<EOF /usr/share/nginx/html/index.html
<html>
    <head>
        <title>Hello from Docker</title>
    </head>
    <body>
        <h1>Hello from Docker</h1>
        <p>Built inside an image</p>
    </body>
</html>
EOF


COPY <<EOF /etc/nginx/nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format logger-json escape=json '{"source": "nginx", "time": \$msec, "resp_body_size": \$body_bytes_sent, "host": "\$http_host", "address": "\$remote_addr", "request_length": \$request_length, "method": "\$request_method", "uri": "\$request_uri", "status": \$status,  "user_agent": "\$http_user_agent", "resp_time": \$request_time, "upstream_addr": "\$upstream_addr"}';

    access_log  /var/log/nginx/access.log  logger-json;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
EOF