services:
    nginx:
        image: "nginx:1.20.1"
        environment:
            - VERSION=nginx:1.20.1
        ports:
            - "8080:80"
        networks:
            - service_bridge
        profiles: [all, backend]

    podinfo_a:
        image: "stefanprodan/podinfo:6.1.4"
        environment:
            - VERSION=0.0.1   
            - PODNAME=info_a                    
        ports:
            - "9001:9898"
        command: [ "./podinfo", "--level=debug" ]            
        networks:
            - service_bridge

networks:
    service_bridge:
        driver: bridge

