FROM ubuntu:20.04

RUN apt-get update && apt-get install htop --no-install-recommends -y 
RUN apt-get install curl lsof strace nano tcpdump iproute2 dnsutils -y
RUN apt-get install apt-file --no-install-recommends -y
RUN apt-file update

WORKDIR /scratch
COPY hold.sh .

CMD [ "/bin/bash", "-c", "/scratch/hold.sh" ]
