#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list


build:
  #!/usr/bin/env bash
  set -eufo pipefail
  docker compose up -d --build --force-recreate


stop: build
  #!/usr/bin/env bash
  set -eufo pipefail  
  docker compose down

test:
  #!/usr/bin/env bash
  set -eufo pipefail  
  hurl --very-verbose --test hurl/test.hurl 
